[default]
description = "Default permissions for the plugin"
permissions = [
	"allow-ping",
	"allow-get-availability",
	"allow-get-devices",
	"allow-request-device",
	"allow-connect-gatt",
	"allow-disconnect-gatt",
	"allow-forget-device",
	"allow-get-primary-services",
	"allow-get-characteristics",
	"allow-read-characteristic-value",
	"allow-write-characteristic-value",
	"allow-start-notifications",
	"allow-stop-notifications",
]
